export const mapDBToModel = {
  roomAvailabilityTable: ({
    id,
    room_id,
    date,
    available_room,
    updated_at,
    created_at,
  }) => ({
    id,
    roomId: room_id,
    date,
    availableRoom: available_room,
    updatedAt: updated_at,
    createdAt: created_at,
  }),

  bookingTable: ({
    id,
    user_id,
    room_id,
    guest_name,
    total_guests,
    special_request,
    check_in_date,
    check_out_date,
    total_price,
    status,
    snap_token,
    check_in_status,
    created_at,
    updated_at,
    item_details,
    customer_details,
    room_type
  }) => ({
    id,
    userId: user_id,
    roomId: room_id,
    guestName: guest_name,
    totalGuests: total_guests,
    specialRequest: special_request,
    checkInDate: check_in_date,
    checkOutDate: check_out_date,
    totalPrice: total_price,
    status,
    snapToken: snap_token,
    checkInStatus: check_in_status,
    createdAt: created_at,
    updatedAt: updated_at,
    itemDetails: item_details,
    customerDetails: customer_details,
    roomType: room_type
  }),

  roomsTable: ({
    id,
    room_type,
    price_per_night,
    capacity,
    total_rooms,
    available_rooms,
    description,
    created_at,
    updated_at,
    primary_picture,
  }) => ({
    id,
    roomType: room_type,
    pricePerNight: Number(price_per_night),
    capacity,
    totalRooms: total_rooms,
    availableRooms: available_rooms,
    description,
    createdAt: created_at,
    updatedAt: updated_at,
    primaryPicture: primary_picture,
  }),

  roomPicturesTable: ({
    id,
    room_id,
    path,
    created_at,
    updated_at,
    is_available,
  }) => ({
    id,
    roomId: room_id,
    path,
    isAvailable: is_available,
    createdAt: created_at,
    updatedAt: updated_at,
  }),

  usersTable: ({
    id,
    fullname,
    email,
    contact_number,
    password,
    created_at,
    updated_at,
  }) => ({
    id,
    fullname,
    email,
    contactNumber: contact_number,
    password,
    createdAt: created_at,
    updatedAt: updated_at,
  }),

  transactionsTable: ({
    id,
    booking_id,
    transaction_code,
    amount,
    status,
    payment_url,
    expiry_time,
    created_at,
    updated_at,
  }) => ({
    id,
    bookingId: booking_id,
    transactionCode: transaction_code,
    amount,
    status,
    paymentUrl: payment_url,
    expiryTime: expiry_time,
    createdAt: created_at,
    updatedAt: updated_at,
  }),
};
