export const mapDBToModel = {
  roomAvailabilityTable: ({
    id,
    room_id,
    date,
    available_room,
    updated_at,
    created_at,
  }) => ({
    id,
    roomId: room_id,
    date,
    availableRoom: available_room,
    updatedAt: updated_at,
    createdAt: created_at,
  }),

  bookingTable: ({
    id,
    user_id,
    room_id,
    guest_name,
    number_of_guest,
    special_request,
    check_in_date,
    check_out_date,
    qris_expires_at,
    total_price,
    status,
    payment_status,
    check_in_status,
    created_at,
    updated_at,
  }) => ({
    id,
    userId: user_id,
    roomId: room_id,
    guestName: guest_name,
    numberOfGuest: number_of_guest,
    specialRequest: special_request,
    checkInDate: check_in_date,
    checkOutDate: check_out_date,
    qrisExpiresAt: qris_expires_at,
    totalPrice: total_price,
    status,
    paymentStatus: payment_status,
    checkInStatus: check_in_status,
    createdAt: created_at,
    updatedAt: updated_at,
  }),

  roomsTable: ({
    id,
    room_type,
    price_per_night,
    capacity,
    total_rooms,
    available_rooms,
    description,
    created_at,
    updated_at,
    primary_picture,
  }) => ({
    id,
    roomType: room_type,
    pricePerNight: price_per_night,
    capacity,
    totalRooms: total_rooms,
    availableRooms: available_rooms,
    description,
    createdAt: created_at,
    updatedAt: updated_at,
    primaryPicture: primary_picture,
  }),

  roomPicturesTable: ({
    id,
    room_id,
    path,
    created_at,
    updated_at,
    is_available,
  }) => ({
    id,
    roomId: room_id,
    path,
    isAvailable: is_available,
    createdAt: created_at,
    updatedAt: updated_at,
  }),

  usersTable: ({
    id,
    fullname,
    email,
    contact_number,
    password,
    created_at,
    updated_at,
  }) => ({
    id,
    fullname,
    email,
    contactNumber: contact_number,
    password,
    createdAt: created_at,
    updatedAt: updated_at,
  }),

  transactionsTable: ({
    id,
    booking_id,
    transaction_code,
    amount,
    status,
    payment_url,
    expiry_time,
    created_at,
    updated_at,
  }) => ({
    id,
    bookingId: booking_id,
    transactionCode: transaction_code,
    amount,
    status,
    paymentUrl: payment_url,
    expiryTime: expiry_time,
    createdAt: created_at,
    updatedAt: updated_at,
  }),
};
